### ISSUE TITLE
Parser$ParserException

### ISSUE THREAD

**Issue by eskimoblood** [jamieowen/threeflow.js#4]
I try to render a one of my threejs experiments (https://github.com/eskimoblood/superdupershape). I added the follwoing lines to the bootstrap:

```
threeflow = new THREEFLOW.SunflowRenderer({
    pngPath: "superduper/renders/superduper.png"
  });
  threeflow.connect();
  threeflow.image.filter = "mitchell";
  threeflow.image.antialiasMin = 1;
  threeflow.image.antialiasMax = 2;
  threeFlowGui = new THREEFLOW.DatGui(threeflow);
  threeFlowGui.onRender = function() {
    return threeflow.render(scene, camera, 500, 500);
  };
```

 Unfortunately I got a Parser$ParserException, it seems that the shader is missing. Any hints on that.

```
SYS    info  : Adding include search path: "/Users/andreaskoberle/projects/private/threeflow.js"
SYS    info  : Adding texture search path: "/Users/andreaskoberle/projects/private/threeflow.js"
API    info  : Parsing ".tmp.render.sc" ...
API    info  : Reading image settings ...
API    info  : Reading pinhole camera ...
API    info  : Reading shader: undefined ...
API    error : Expecting type found }
org.sunflow.system.Parser$ParserException: Expecting type found }
        at org.sunflow.system.Parser.checkNextToken(Unknown Source)
        at org.sunflow.core.parser.SCParser.parseShader(Unknown Source)
        at org.sunflow.core.parser.SCParser.parse(Unknown Source)
        at org.sunflow.SunflowAPI.parse(Unknown Source)
        at org.sunflow.SunflowAPI.create(Unknown Source)
        at SunflowGUI.main(Unknown Source)
```

The data that is send from the browser looks like this: 

```
image {
  resolution 500 500
  aa 1 2
  samples 2
  contrast 0.1
  filter mitchell
  jitter true
}

camera {
  type pinhole
  eye 0 0 300
  target 0 0 299
  up 0 1 0
  fov 34.712643678160916
  aspect 0.7713920817369093
}

shader {
  name undefined
}

object {
  noinstance
  type generic-mesh
  name undefined
  points 100
    0 50 0
    42.211206700704984 50.30535723330196 32.13938048432696
    14.659798241399068 2.584917961701162 49.2403876506104
    -21.650635094610962 12.499999999999986 43.301270189221945
    -27.55140845930594 75.69687261611413 17.101007166283434
    27.551408459305904 75.69687261611405 -17.101007166283434
    21.650635094610983 12.500000000000028 -43.30127018922192
    -14.659798241399066 2.584917961701156 -49.2403876506104
    -42.21120670070492 50.305357233301855 -32.13938048432697
    -1.224646798818428e-14 50 -1.224646798818428e-14
    0 47.195769133178715 39.601952472778315
    11.790253101494594 14.051076491301211 60.6737112568674
    -52.01239651757228 -9.171188837354997 53.35556623067902
    -50.13783186482288 28.94709072373966 21.071758784089084
    -33.948680774839936 93.27323384914597 -21.07175878408908
    18.06371574273248 49.629651114604485 -53.35556623067899
    -9.265096844344592 -5.34920615715031 -60.6737112568674
    -79.68761465117447 14.051076491301199 -39.60195247277833
    -67.89736154967967 80.91692455449869 -1.509002463392166e-14
    -1.1559629517344179e-14 47.19576913317872 39.601952472778315
    0 8.793883020075464 49.87258889559886
    -27.905143179120643 -33.256054635572845 43.85721863376813
    -80.34965743390843 -14.16781249628054 17.320568354505454
    -41.21230471834615 23.79393522306201 -17.320568354505433
    -14.84801655448905 40.79459020714708 -43.8572186337681
    -5.156662033310849 -14.167812496280519 -49.87258889559886
    -33.59657862505214 -19.396993713024308 -32.55202054109341
    -85.50631946721947 15.077071143148217 -1.2403701362620264e-14
    -42.753159733609614 50.951231707283355 32.5520205410934
    -2.1538801379438295e-15 8.793883020075464 49.87258889559886
    0 -28.17404384973609 48.7988754024164
    -58.35375330183718 -69.54329513882071 19.27218103110084
    -89.40313690401612 -15.764185196150702 -19.272181031100814
    -24.399437701208228 14.087021924868063 -48.79887540241637
    5.737694178858769 -15.764185196150697 -55.49203363385207
    -25.311689423320214 -69.5432951388207 -36.21985260275124
    -48.79887540241637 -28.17404384973614 -1.3801301044139738e-14
    -72.88210496475787 12.851081516113151 36.21985260275118
    -10.783337760399688 12.851081516113124 55.49203363385207
    6.900650522069858e-15 -28.174043849736062 48.798875402416414
    0 -49.4841556001522 18.010759706252607
    -54.53432732814572 -64.99148051302627 -18.010759706252603
    -44.456790960025316 -7.838931721968644 -45.60484448490461
    7.919198137587431 -4.572151176502082 -51.8599156876801
    23.65496438763353 -64.99148051302636 -33.84915598142751
    -30.879362940512227 -84.84035240620123 -1.2897965016959756e-14
    -34.93533769696638 -20.169926623574046 33.84915598142746
    -15.439681470256136 2.7224324167506917 51.8599156876801
    29.017109489769105 -34.58124448113186 45.604844484904646
    1.2120122549591878e-14 -49.48415560015221 18.0107597062526
    0 -49.4841556001522 -18.010759706252603
    -29.017109489769222 -34.58124448113202 -45.60484448490461
    15.439681470256067 2.7224324167506855 -51.8599156876801
    34.93533769696637 -20.169926623573996 -33.84915598142751
    30.879362940512273 -84.84035240620136 -1.2897965016959756e-14
    -23.6549643876335 -64.99148051302627 33.8491559814275
    -7.9191981375874425 -4.5721511765021 51.8599156876801
    44.45679096002531 -7.838931721968624 45.604844484904646
    54.53432732814565 -64.99148051302615 18.0107597062526
    1.212012254959188e-14 -49.484155600152214 -18.010759706252564
    0 -28.174043849736158 -48.7988754024164
    10.783337760399684 12.851081516113126 -55.4920336338521
    72.88210496475767 12.851081516113146 -36.21985260275126
    48.798875402416435 -28.174043849736112 -1.3801301044139746e-14
    25.311689423320296 -69.54329513882091 36.21985260275121
    -5.737694178858776 -15.764185196150722 55.4920336338521
    24.39943770120816 14.087021924868056 48.79887540241644
    89.40313690401638 -15.764185196150713 19.27218103110084
    58.35375330183713 -69.54329513882061 -19.272181031100803
    6.900650522069892e-15 -28.1740438497362 -48.79887540241638
    0 8.793883020075445 -49.87258889559886
    42.75315973360967 50.95123170728345 -32.55202054109341
    85.50631946721927 15.077071143148215 -1.2403701362620264e-14
    33.5965786250522 -19.396993713024298 32.55202054109336
    5.1566620333108695 -14.167812496280572 49.87258889559886
    14.848016554488986 40.79459020714692 43.857218633768134
    41.212304718346125 23.79393522306205 17.320568354505447
    80.34965743390862 -14.167812496280542 -17.32056835450542
    27.9051431791207 -33.256054635572895 -43.85721863376808
    -2.153880137943822e-15 8.793883020075434 -49.87258889559887
    0 47.195769133178715 -39.60195247277833
    67.89736154967976 80.91692455449883 -1.509002463392166e-14
    79.6876146511743 14.0510764913012 39.601952472778315
    9.265096844344617 -5.349206157150313 60.6737112568674
    -18.06371574273246 49.629651114604414 53.35556623067903
    33.94868077483988 93.27323384914584 21.071758784089077
    50.13783186482286 28.947090723739713 -21.071758784089038
    52.01239651757257 -9.171188837355027 -53.35556623067896
    -11.790253101494537 14.051076491301135 -60.67371125686741
    -1.1559629517344184e-14 47.195769133178736 -39.6019524727783
    0 50 -1.224646798818428e-14
    42.211206700704984 50.30535723330196 32.13938048432696
    14.659798241399068 2.584917961701162 49.2403876506104
    -21.65063509461094 12.499999999999973 43.30127018922196
    -27.551408459305947 75.69687261611415 17.101007166283427
    27.551408459305907 75.69687261611405 -17.101007166283395
    21.65063509461102 12.500000000000048 -43.301270189221896
    -14.659798241399049 2.584917961701153 -49.24038765061041
    -42.211206700704935 50.305357233301876 -32.13938048432695
    -1.224646798818428e-14 50 -2.449293597636856e-14
  triangles 81
    10 11 1
    11 12 2
    12 13 3
    13 14 4
    14 15 5
    15 16 6
    16 17 7
    17 18 8
    18 19 9
    20 21 11
    21 22 12
    22 23 13
    23 24 14
    24 25 15
    25 26 16
    26 27 17
    27 28 18
    28 29 19
    30 31 21
    31 32 22
    32 33 23
    33 34 24
    34 35 25
    35 36 26
    36 37 27
    37 38 28
    38 39 29
    40 41 31
    41 42 32
    42 43 33
    43 44 34
    44 45 35
    45 46 36
    46 47 37
    47 48 38
    48 49 39
    50 51 41
    51 52 42
    52 53 43
    53 54 44
    54 55 45
    55 56 46
    56 57 47
    57 58 48
    58 59 49
    60 61 51
    61 62 52
    62 63 53
    63 64 54
    64 65 55
    65 66 56
    66 67 57
    67 68 58
    68 69 59
    70 71 61
    71 72 62
    72 73 63
    73 74 64
    74 75 65
    75 76 66
    76 77 67
    77 78 68
    78 79 69
    80 81 71
    81 82 72
    82 83 73
    83 84 74
    84 85 75
    85 86 76
    86 87 77
    87 88 78
    88 89 79
    90 91 81
    91 92 82
    92 93 83
    93 94 84
    94 95 85
    95 96 86
    96 97 87
    97 98 88
    98 99 89
  normals none
  uvs none
}

instance {
  name undefined
  geometry undefined
  transform col 0.9637709259986877 0.18947355449199677 0.18773767352104187 0 0 0.7038453221321106 -0.7103532552719116 0 -0.2667314410209656 0.684617817401886 0.6783456206321716 0 0 0 0 1
  shader undefined
}
```

**Comment by eskimoblood** [comment]
Also creating the mesh without shader seems to work.

**Comment by jamieowen** [comment]
From looking at your code, It's the ShaderMaterial that was causing the problem. You won't be able to use custom web gl shaders with this.  As sunflow has its own shader programming language.

Stick to the materials defined in threeflow for now. 

Also keep in mind this is not fully ready yet! :)  I'm just finishing a first version over the next couple of days.  I'll be adding better error messages when parsing the three js scene to cover as many edge cases. 

I've added proper normals support as well so geometry will render much more smoothly! :)

**Comment by jamieowen** [comment]
Also, I just realised something else..
The names of your meshes / materials are not being assigned either.

Seems like you are using an old version of THREE.js ( rev 57 ) with no Geometry.UUID / Material.UUID properties. ( threeflow uses them to identity your scene objects )

So make sure to use the latest version of THREE as well.

**Comment by eskimoblood** [comment]
Thanks
